In [1]:
import os

import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest
from sklearn.ensemble import RandomForestRegressor

import joblib

In [ ]:
gaze_df = pd.read_csv('COLET/gaze_dataset.csv', sep=',')
pupil_df = pd.read_csv('COLET/pupil_dataset.csv', sep=',')
blinks_df = pd.read_csv('COLET/blinks_dataset.csv', sep=',')
annotation_df = pd.read_csv('COLET/annotation_dataset.csv', sep=',')

In [ ]:
print('Gaze:')
print(gaze_df.columns.to_list())
display(gaze_df.head())

print('Pupil:')
print(pupil_df.columns.to_list())
display(pupil_df.head())

print('Blinks:')
print(blinks_df.columns.to_list())
display(blinks_df.head())

print('Annotation:')
print(annotation_df.columns.to_list())
display(annotation_df.head())

Gaze:
['VisualAcuity_logMAR_', 'Gender', 'Age', 'Education', 'task_number', 'gaze_timestamp', 'world_index', 'confidence', 'norm_pos_x', 'norm_pos_y', 'base_data', 'gaze_point_3d_x', 'gaze_point_3d_y', 'gaze_point_3d_z', 'eye_center0_3d_x', 'eye_center0_3d_y', 'eye_center0_3d_z', 'gaze_normal0_x', 'gaze_normal0_y', 'gaze_normal0_z', 'eye_center1_3d_x', 'eye_center1_3d_y', 'eye_center1_3d_z', 'gaze_normal1_x', 'gaze_normal1_y', 'gaze_normal1_z']

,VisualAcuity_logMAR_,Gender,Age,Education,task_number,gaze_timestamp,world_index,confidence,norm_pos_x,norm_pos_y,...,eye_center0_3d_z,gaze_normal0_x,gaze_normal0_y,gaze_normal0_z,eye_center1_3d_x,eye_center1_3d_y,eye_center1_3d_z,gaze_normal1_x,gaze_normal1_y,gaze_normal1_z
0,-0.04,F,28,18,1,5410.551715,0,0.999499,0.446264,0.846886,...,-19.037289,-0.235298,-0.420213,0.876388,-39.195621,15.099793,-21.6003,0.277597,-0.391313,0.877391
1,-0.04,F,28,18,1,5410.555834,0,0.999653,0.446534,0.847007,...,-19.037289,-0.234840,-0.420298,0.876470,-39.195621,15.099793,-21.6003,0.277597,-0.391313,0.877391
2,-0.04,F,28,18,1,5410.559774,0,0.999648,0.446660,0.846410,...,-19.037289,-0.234840,-0.420298,0.876470,-39.195621,15.099793,-21.6003,0.278049,-0.390575,0.877576
3,-0.04,F,28,18,1,5410.563583,0,0.999656,0.446442,0.845542,...,-19.037289,-0.235225,-0.419217,0.876885,-39.195621,15.099793,-21.6003,0.278049,-0.390575,0.877576
4,-0.04,F,28,18,1,5410.568291,0,0.999565,0.446472,0.845614,...,-19.037289,-0.235225,-0.419217,0.876885,-39.195621,15.099793,-21.6003,0.278153,-0.390681,0.877496

Pupil:
['VisualAcuity_logMAR_', 'Gender', 'Age', 'Education', 'task_number', 'pupil_timestamp', 'world_index', 'eye_id', 'confidence', 'norm_pos_x', 'norm_pos_y', 'diameter', 'method', 'ellipse_center_x', 'ellipse_center_y', 'ellipse_axis_a', 'ellipse_axis_b', 'ellipse_angle', 'diameter_3d', 'model_confidence', 'model_id', 'sphere_center_x', 'sphere_center_y', 'sphere_center_z', 'sphere_radius', 'circle_3d_center_x', 'circle_3d_center_y', 'circle_3d_center_z', 'circle_3d_normal_x', 'circle_3d_normal_y', 'circle_3d_normal_z', 'circle_3d_radius', 'theta', 'phi', 'projected_sphere_center_x', 'projected_sphere_center_y', 'projected_sphere_axis_a', 'projected_sphere_axis_b', 'projected_sphere_angle']

,VisualAcuity_logMAR_,Gender,Age,Education,task_number,pupil_timestamp,world_index,eye_id,confidence,norm_pos_x,...,circle_3d_normal_y,circle_3d_normal_z,circle_3d_radius,theta,phi,projected_sphere_center_x,projected_sphere_center_y,projected_sphere_axis_a,projected_sphere_axis_b,projected_sphere_angle
0,-0.04,F,28,18,1,5410.553797,0,1,1.000000,0.406205,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-0.04,F,28,18,1,5410.553797,0,1,0.999646,0.406235,...,-0.150923,-0.714380,1.971798,1.419294,-2.333954,145.942173,79.574077,187.867489,187.867489,90.0
2,-0.04,F,28,18,1,5410.557872,0,0,0.999661,0.326001,...,0.196366,-0.699703,1.889488,1.768446,-2.346975,134.652012,92.929580,188.411042,188.411042,90.0
3,-0.04,F,28,18,1,5410.557872,0,0,1.000000,0.325980,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-0.04,F,28,18,1,5410.561675,0,1,1.000000,0.406046,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN