In [19]:
import os

import numpy as np

import pandas as pd

from sklearn.model_selection import train_test_split

In [30]:
colet_path = '/work/cvcs2026/LZMM/COLET/dumped/'

gaze_df = pd.read_csv(os.path.join(colet_path, 'gaze_dataset.csv'), sep=',')
pupil_df = pd.read_csv(os.path.join(colet_path, 'pupil_dataset.csv'), sep=',')
blinks_df = pd.read_csv(os.path.join(colet_path, 'blinks_dataset.csv'), sep=',')
annotation_df = pd.read_csv(os.path.join(colet_path, 'annotation_dataset.csv'), sep=',')    # ground truth

In [31]:
metrics = ['mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', 'mean']

for m in metrics:
    annotation_df[m] = annotation_df.apply(
        lambda row: row[f"{m}_{int(row['task_number'])}"], 
        axis=1
    )

cols_to_drop = [f"{m}_{i}" for m in metrics for i in range(1, 5)]
annotation_df = annotation_df.drop(columns=cols_to_drop)

In [32]:
print('Gaze:')
print(gaze_df.columns.to_list())
display(gaze_df.head(3))

print('Pupil:')
print(pupil_df.columns.to_list())
display(pupil_df.head(3))

print('Blinks:')
print(blinks_df.columns.to_list())
display(blinks_df.head(3))

print('Annotation:')
print(annotation_df.columns.to_list())
display(annotation_df.head(4))

Gaze:
['subject_id', 'VisualAcuity_logMAR_', 'Gender', 'Age', 'Education', 'task_number', 'gaze_timestamp', 'world_index', 'confidence', 'norm_pos_x', 'norm_pos_y', 'base_data', 'gaze_point_3d_x', 'gaze_point_3d_y', 'gaze_point_3d_z', 'eye_center0_3d_x', 'eye_center0_3d_y', 'eye_center0_3d_z', 'gaze_normal0_x', 'gaze_normal0_y', 'gaze_normal0_z', 'eye_center1_3d_x', 'eye_center1_3d_y', 'eye_center1_3d_z', 'gaze_normal1_x', 'gaze_normal1_y', 'gaze_normal1_z']

,subject_id,VisualAcuity_logMAR_,Gender,Age,Education,task_number,gaze_timestamp,world_index,confidence,norm_pos_x,...,eye_center0_3d_z,gaze_normal0_x,gaze_normal0_y,gaze_normal0_z,eye_center1_3d_x,eye_center1_3d_y,eye_center1_3d_z,gaze_normal1_x,gaze_normal1_y,gaze_normal1_z
0,1,-0.04,F,28,18,1,5410.551715,0,0.999499,0.446264,...,-19.037289,-0.235298,-0.420213,0.876388,-39.195621,15.099793,-21.6003,0.277597,-0.391313,0.877391
1,1,-0.04,F,28,18,1,5410.555834,0,0.999653,0.446534,...,-19.037289,-0.234840,-0.420298,0.876470,-39.195621,15.099793,-21.6003,0.277597,-0.391313,0.877391
2,1,-0.04,F,28,18,1,5410.559774,0,0.999648,0.446660,...,-19.037289,-0.234840,-0.420298,0.876470,-39.195621,15.099793,-21.6003,0.278049,-0.390575,0.877576

Pupil:
['subject_id', 'VisualAcuity_logMAR_', 'Gender', 'Age', 'Education', 'task_number', 'pupil_timestamp', 'world_index', 'eye_id', 'confidence', 'norm_pos_x', 'norm_pos_y', 'diameter', 'method', 'ellipse_center_x', 'ellipse_center_y', 'ellipse_axis_a', 'ellipse_axis_b', 'ellipse_angle', 'diameter_3d', 'model_confidence', 'model_id', 'sphere_center_x', 'sphere_center_y', 'sphere_center_z', 'sphere_radius', 'circle_3d_center_x', 'circle_3d_center_y', 'circle_3d_center_z', 'circle_3d_normal_x', 'circle_3d_normal_y', 'circle_3d_normal_z', 'circle_3d_radius', 'theta', 'phi', 'projected_sphere_center_x', 'projected_sphere_center_y', 'projected_sphere_axis_a', 'projected_sphere_axis_b', 'projected_sphere_angle']

,subject_id,VisualAcuity_logMAR_,Gender,Age,Education,task_number,pupil_timestamp,world_index,eye_id,confidence,...,circle_3d_normal_y,circle_3d_normal_z,circle_3d_radius,theta,phi,projected_sphere_center_x,projected_sphere_center_y,projected_sphere_axis_a,projected_sphere_axis_b,projected_sphere_angle
0,1,-0.04,F,28,18,1,5410.553797,0,1,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,-0.04,F,28,18,1,5410.553797,0,1,0.999646,...,-0.150923,-0.714380,1.971798,1.419294,-2.333954,145.942173,79.574077,187.867489,187.867489,90.0
2,1,-0.04,F,28,18,1,5410.557872,0,0,0.999661,...,0.196366,-0.699703,1.889488,1.768446,-2.346975,134.652012,92.929580,188.411042,188.411042,90.0

Blinks:
['subject_id', 'VisualAcuity_logMAR_', 'Gender', 'Age', 'Education', 'task_number', 'id', 'start_timestamp', 'duration', 'end_timestamp', 'start_frame_index', 'index', 'end_frame_index', 'confidence', 'filter_response', 'base_data']

,subject_id,VisualAcuity_logMAR_,Gender,Age,Education,task_number,id,start_timestamp,duration,end_timestamp,start_frame_index,index,end_frame_index,confidence,filter_response,base_data
0,1,-0.04,F,28,18,1,1,5437.625617,0.236131,5437.861748,37,40,44,0.703872,0.5068225043614704 0.5512669488059149 0.595711...,5437.625617 5437.629564 5437.633621 5437.63786...
1,1,-0.04,F,28,18,1,2,5444.161561,0.180073,5444.341634,231,233,236,0.553669,0.5048782729116744 0.5493227173561188 0.592878...,5444.161561 5444.165642 5444.169793 5444.17554...
2,1,-0.04,F,28,18,3,1,4937.633752,0.219501,4937.853253,355,358,362,0.632858,0.5145911521303596 0.559035596574804 0.6034800...,4937.633752 4937.637365 4937.642261 4937.64540...

Annotation:
['subject_id', 'VisualAcuity_logMAR_', 'Gender', 'Age', 'Education', 'task_number', 'mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', 'mean']

,subject_id,VisualAcuity_logMAR_,Gender,Age,Education,task_number,mental,physical,temporal,performance,effort,frustration,mean
0,1,-0.04,F,28,18,1,10.0,5.0,15.0,25.0,25.0,10.0,15.0
1,1,-0.04,F,28,18,2,50.0,30.0,25.0,50.0,15.0,25.0,32.5
2,1,-0.04,F,28,18,3,100.0,10.0,75.0,80.0,90.0,20.0,62.5
3,1,-0.04,F,28,18,4,60.0,15.0,45.0,50.0,20.0,25.0,35.8

In [44]:
gaze_drop = ['Education', 'world_index', 'norm_pos_x', 'norm_pos_y', 'base_data', 'gaze_point_3d_x', 'gaze_point_3d_y', 'gaze_point_3d_z', 'eye_center0_3d_x', 'eye_center0_3d_y', 'eye_center0_3d_z', 'gaze_normal0_x', 'gaze_normal0_y', 'gaze_normal0_z', 'eye_center1_3d_x', 'eye_center1_3d_y', 'eye_center1_3d_z', 'gaze_normal1_x', 'gaze_normal1_y', 'gaze_normal1_z']
gaze_df_reduced = gaze_df.drop(columns=gaze_drop)

pupil_drop = ['VisualAcuity_logMAR_', 'confidence', 'Education', 'world_index', 'norm_pos_x', 'norm_pos_y', 'method', 'ellipse_center_x', 'ellipse_center_y', 'ellipse_axis_a', 'ellipse_axis_b', 'ellipse_angle', 'diameter_3d', 'model_confidence', 'model_id', 'sphere_center_x', 'sphere_center_y', 'sphere_center_z', 'sphere_radius', 'circle_3d_center_x', 'circle_3d_center_y', 'circle_3d_center_z', 'circle_3d_normal_x', 'circle_3d_normal_y', 'circle_3d_normal_z', 'circle_3d_radius', 'theta', 'phi', 'projected_sphere_center_x', 'projected_sphere_center_y', 'projected_sphere_axis_a', 'projected_sphere_axis_b', 'projected_sphere_angle']
pupil_df_reduced = pupil_df.drop(columns=pupil_drop)

blinks_drop = ['Education', 'id', 'end_timestamp', 'start_frame_index', 'index', 'end_frame_index', 'filter_response', 'base_data']
blinks_df_reduced = blinks_df.drop(columns=blinks_drop)

gaze_df_reduced = gaze_df_reduced.sort_values(['subject_id', 'task_number', 'gaze_timestamp'], ascending=True)
pupil_df_reduced = pupil_df_reduced.sort_values(['subject_id', 'task_number', 'pupil_timestamp'], ascending=True)
blinks_df_reduced = blinks_df_reduced.sort_values(['subject_id', 'task_number', 'start_timestamp'], ascending=True)

print('Gaze:')
display(gaze_df_reduced.dtypes)
display(gaze_df_reduced.head(3))
print('Pupil:')
display(pupil_df_reduced.dtypes)
display(pupil_df_reduced.head(3))
print('Blinks:')
display(blinks_df_reduced.dtypes)
display(blinks_df_reduced.head(3))

Gaze:

subject_id                int64
VisualAcuity_logMAR_    float64
Gender                      str
Age                       int64
task_number               int64
gaze_timestamp          float64
confidence              float64
dtype: object

,subject_id,VisualAcuity_logMAR_,Gender,Age,task_number,gaze_timestamp,confidence
0,1,-0.04,F,28,1,5410.551715,0.999499
1,1,-0.04,F,28,1,5410.555834,0.999653
2,1,-0.04,F,28,1,5410.559774,0.999648

Pupil:

subject_id           int64
Gender                 str
Age                  int64
task_number          int64
pupil_timestamp    float64
eye_id               int64
diameter           float64
dtype: object

   subject_id Gender  Age  task_number  pupil_timestamp  eye_id   diameter
0           1      F   28            1      5410.553797       1  40.757561
1           1      F   28            1      5410.553797       1  40.764095
2           1      F   28            1      5410.557872       0  38.729047

Blinks:

subject_id                int64
VisualAcuity_logMAR_    float64
Gender                      str
Age                       int64
task_number               int64
start_timestamp         float64
duration                float64
confidence              float64
dtype: object

,subject_id,VisualAcuity_logMAR_,Gender,Age,task_number,start_timestamp,duration,confidence
0,1,-0.04,F,28,1,5437.625617,0.236131,0.703872
1,1,-0.04,F,28,1,5444.161561,0.180073,0.553669
2,1,-0.04,F,28,3,4937.633752,0.219501,0.632858

In [45]:
label = annotation_df.drop(columns=['VisualAcuity_logMAR_', 'Gender', 'Age', 'Education', 'physical', 'temporal', 'performance', 'effort', 'frustration', 'mean'])
label['cload'] = (label['mental'] >= 50).astype(int)
label = label.drop(columns=['mental'])
label.head(2)

   subject_id  task_number  cload
0           1            1      0
1           1            2      1

In [46]:
pupil_df_reduced = pupil_df_reduced.merge(label, on=['subject_id', 'task_number'])
pupil_df_reduced.head(1)

,subject_id,Gender,Age,task_number,pupil_timestamp,eye_id,diameter,cload
0,1,F,28,1,5410.553797,1,40.757561,0

In [47]:
pupil_activities = []

for subj in range(1, 48):
    for task in range(1, 5):
        for eye in range(2):
            pupil_activity = pupil_df_reduced[(pupil_df_reduced.subject_id == subj) & (pupil_df_reduced.task_number == task) & (pupil_df_reduced.eye_id == eye)].reset_index(drop=True)
            pupil_activity = pupil_activity.sort_values('pupil_timestamp')
            pupil_activities.append(pupil_activity)
print('Activities number:', len(pupil_activities))

for pupil_activity in pupil_activities[:4]:
    display(pupil_activity.head(1))
    print(len(pupil_activity))

Activities number: 376

,subject_id,Gender,Age,task_number,pupil_timestamp,eye_id,diameter,cload
0,1,F,28,1,5410.557872,0,38.729047,0

8202

,subject_id,Gender,Age,task_number,pupil_timestamp,eye_id,diameter,cload
0,1,F,28,1,5410.553797,1,40.757561,0

8204

,subject_id,Gender,Age,task_number,pupil_timestamp,eye_id,diameter,cload
0,1,F,28,2,4659.173514,0,37.972534,1

6870

,subject_id,Gender,Age,task_number,pupil_timestamp,eye_id,diameter,cload
0,1,F,28,2,4659.169934,1,39.58567,1

6874

In [ ]:
# TODO: 
#   - reduce framerate 
#   - handle the right-left eye issue (if train contains left and test right, then results won't be realistic)

In [ ]:
len(np.array_split(pupil_activities[0], len(pupil_activities[0]) // 24))

256

In [ ]:
# split in clips