In [1]:
import os

import pandas as pd

from sklearn.model_selection import train_test_split

In [2]:
colet_path = '/work/cvcs2026/LZMM/COLET/dumped/'

gaze_df = pd.read_csv(os.path.join(colet_path, 'gaze_dataset.csv'), sep=',')
pupil_df = pd.read_csv(os.path.join(colet_path, 'pupil_dataset.csv'), sep=',')
blinks_df = pd.read_csv(os.path.join(colet_path, 'blinks_dataset.csv'), sep=',')
annotation_df = pd.read_csv(os.path.join(colet_path, 'annotation_dataset.csv'), sep=',')    # ground truth

In [3]:
metrics = ['mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', 'mean']

for m in metrics:
    annotation_df[m] = annotation_df.apply(
        lambda row: row[f"{m}_{int(row['task_number'])}"], 
        axis=1
    )

cols_to_drop = [f"{m}_{i}" for m in metrics for i in range(1, 5)]
annotation_df = annotation_df.drop(columns=cols_to_drop)

In [4]:
print('Gaze:')
print(gaze_df.columns.to_list())
display(gaze_df.head(3))

print('Pupil:')
print(pupil_df.columns.to_list())
display(pupil_df.head(3))

print('Blinks:')
print(blinks_df.columns.to_list())
display(blinks_df.head(3))

print('Annotation:')
print(annotation_df.columns.to_list())
display(annotation_df.head(4))

Gaze:
['subject_id', 'VisualAcuity_logMAR_', 'Gender', 'Age', 'Education', 'task_number', 'gaze_timestamp', 'world_index', 'confidence', 'norm_pos_x', 'norm_pos_y', 'base_data', 'gaze_point_3d_x', 'gaze_point_3d_y', 'gaze_point_3d_z', 'eye_center0_3d_x', 'eye_center0_3d_y', 'eye_center0_3d_z', 'gaze_normal0_x', 'gaze_normal0_y', 'gaze_normal0_z', 'eye_center1_3d_x', 'eye_center1_3d_y', 'eye_center1_3d_z', 'gaze_normal1_x', 'gaze_normal1_y', 'gaze_normal1_z']

   subject_id  VisualAcuity_logMAR_  ... gaze_normal1_y  gaze_normal1_z
0           1                 -0.04  ...      -0.391313        0.877391
1           1                 -0.04  ...      -0.391313        0.877391
2           1                 -0.04  ...      -0.390575        0.877576

[3 rows x 27 columns]

Pupil:
['subject_id', 'VisualAcuity_logMAR_', 'Gender', 'Age', 'Education', 'task_number', 'pupil_timestamp', 'world_index', 'eye_id', 'confidence', 'norm_pos_x', 'norm_pos_y', 'diameter', 'method', 'ellipse_center_x', 'ellipse_center_y', 'ellipse_axis_a', 'ellipse_axis_b', 'ellipse_angle', 'diameter_3d', 'model_confidence', 'model_id', 'sphere_center_x', 'sphere_center_y', 'sphere_center_z', 'sphere_radius', 'circle_3d_center_x', 'circle_3d_center_y', 'circle_3d_center_z', 'circle_3d_normal_x', 'circle_3d_normal_y', 'circle_3d_normal_z', 'circle_3d_radius', 'theta', 'phi', 'projected_sphere_center_x', 'projected_sphere_center_y', 'projected_sphere_axis_a', 'projected_sphere_axis_b', 'projected_sphere_angle']

   subject_id  ...  projected_sphere_angle
0           1  ...                     NaN
1           1  ...                    90.0
2           1  ...                    90.0

[3 rows x 40 columns]

Blinks:
['subject_id', 'VisualAcuity_logMAR_', 'Gender', 'Age', 'Education', 'task_number', 'id', 'start_timestamp', 'duration', 'end_timestamp', 'start_frame_index', 'index', 'end_frame_index', 'confidence', 'filter_response', 'base_data']

   subject_id  ...                                          base_data
0           1  ...  5437.625617 5437.629564 5437.633621 5437.63786...
1           1  ...  5444.161561 5444.165642 5444.169793 5444.17554...
2           1  ...  4937.633752 4937.637365 4937.642261 4937.64540...

[3 rows x 16 columns]

Annotation:
['subject_id', 'VisualAcuity_logMAR_', 'Gender', 'Age', 'Education', 'task_number', 'mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', 'mean']

   subject_id  VisualAcuity_logMAR_ Gender  ...  effort  frustration  mean
0           1                 -0.04      F  ...    25.0         10.0  15.0
1           1                 -0.04      F  ...    15.0         25.0  32.5
2           1                 -0.04      F  ...    90.0         20.0  62.5
3           1                 -0.04      F  ...    20.0         25.0  35.8

[4 rows x 13 columns]

In [5]:
gaze_drop = ['Education', 'world_index', 'norm_pos_x', 'norm_pos_y', 'base_data', 'gaze_point_3d_x', 'gaze_point_3d_y', 'gaze_point_3d_z', 'eye_center0_3d_x', 'eye_center0_3d_y', 'eye_center0_3d_z', 'gaze_normal0_x', 'gaze_normal0_y', 'gaze_normal0_z', 'eye_center1_3d_x', 'eye_center1_3d_y', 'eye_center1_3d_z', 'gaze_normal1_x', 'gaze_normal1_y', 'gaze_normal1_z']
gaze_df_reduced = gaze_df.drop(columns=gaze_drop)

pupil_drop = ['Education', 'world_index', 'norm_pos_x', 'norm_pos_y', 'method', 'ellipse_center_x', 'ellipse_center_y', 'ellipse_axis_a', 'ellipse_axis_b', 'ellipse_angle', 'diameter_3d', 'model_confidence', 'model_id', 'sphere_center_x', 'sphere_center_y', 'sphere_center_z', 'sphere_radius', 'circle_3d_center_x', 'circle_3d_center_y', 'circle_3d_center_z', 'circle_3d_normal_x', 'circle_3d_normal_y', 'circle_3d_normal_z', 'circle_3d_radius', 'theta', 'phi', 'projected_sphere_center_x', 'projected_sphere_center_y', 'projected_sphere_axis_a', 'projected_sphere_axis_b', 'projected_sphere_angle']
pupil_df_reduced = pupil_df.drop(columns=pupil_drop)

blinks_drop = ['Education', 'id', 'end_timestamp', 'start_frame_index', 'index', 'end_frame_index', 'filter_response', 'base_data']
blinks_df_reduced = blinks_df.drop(columns=blinks_drop)

gaze_df_reduced = gaze_df_reduced.sort_values(['subject_id', 'task_number', 'gaze_timestamp'], ascending=True)
pupil_df_reduced = pupil_df_reduced.sort_values(['subject_id', 'task_number', 'pupil_timestamp'], ascending=True)
blinks_df_reduced = blinks_df_reduced.sort_values(['subject_id', 'task_number', 'start_timestamp'], ascending=True)

print('Gaze:')
display(gaze_df_reduced.dtypes)
display(gaze_df_reduced.head(3))
print('Pupil:')
display(pupil_df_reduced.dtypes)
display(pupil_df_reduced.head(3))
print('Blinks:')
display(blinks_df_reduced.dtypes)
display(blinks_df_reduced.head(3))

Gaze:

subject_id                int64
VisualAcuity_logMAR_    float64
Gender                      str
Age                       int64
task_number               int64
gaze_timestamp          float64
confidence              float64
dtype: object

   subject_id  VisualAcuity_logMAR_  ... gaze_timestamp  confidence
0           1                 -0.04  ...    5410.551715    0.999499
1           1                 -0.04  ...    5410.555834    0.999653
2           1                 -0.04  ...    5410.559774    0.999648

[3 rows x 7 columns]

Pupil:

subject_id                int64
VisualAcuity_logMAR_    float64
Gender                      str
Age                       int64
task_number               int64
pupil_timestamp         float64
eye_id                    int64
confidence              float64
diameter                float64
dtype: object

   subject_id  VisualAcuity_logMAR_ Gender  ...  eye_id  confidence   diameter
0           1                 -0.04      F  ...       1    1.000000  40.757561
1           1                 -0.04      F  ...       1    0.999646  40.764095
2           1                 -0.04      F  ...       0    0.999661  38.729047

[3 rows x 9 columns]

Blinks:

subject_id                int64
VisualAcuity_logMAR_    float64
Gender                      str
Age                       int64
task_number               int64
start_timestamp         float64
duration                float64
confidence              float64
dtype: object

   subject_id  VisualAcuity_logMAR_  ...  duration  confidence
0           1                 -0.04  ...  0.236131    0.703872
1           1                 -0.04  ...  0.180073    0.553669
2           1                 -0.04  ...  0.219501    0.632858

[3 rows x 8 columns]

In [6]:
pupil_activities = []

for subj in range(1, 48):
    for task in range(1, 5):
        for eye in range(2):
            pupil_activities.append(pupil_df_reduced[(pupil_df_reduced.subject_id == subj) & (pupil_df_reduced.task_number == task) & (pupil_df_reduced.eye_id == eye)].reset_index(drop=True))
print('Activities number:', len(pupil_activities))

for pupil_activity in pupil_activities[:9]:
    display(pupil_activity.head(1))

Activities number: 376

   subject_id  VisualAcuity_logMAR_ Gender  ...  eye_id  confidence   diameter
0           1                 -0.04      F  ...       0    0.999661  38.729047

[1 rows x 9 columns]

   subject_id  VisualAcuity_logMAR_ Gender  ...  eye_id  confidence   diameter
0           1                 -0.04      F  ...       1         1.0  40.757561

[1 rows x 9 columns]

   subject_id  VisualAcuity_logMAR_ Gender  ...  eye_id  confidence   diameter
0           1                 -0.04      F  ...       0         1.0  37.972534

[1 rows x 9 columns]

   subject_id  VisualAcuity_logMAR_ Gender  ...  eye_id  confidence  diameter
0           1                 -0.04      F  ...       1         1.0  39.58567

[1 rows x 9 columns]

   subject_id  VisualAcuity_logMAR_ Gender  ...  eye_id  confidence   diameter
0           1                 -0.04      F  ...       0         1.0  38.975426

[1 rows x 9 columns]

   subject_id  VisualAcuity_logMAR_ Gender  ...  eye_id  confidence  diameter
0           1                 -0.04      F  ...       1    0.999716  39.98498

[1 rows x 9 columns]

   subject_id  VisualAcuity_logMAR_ Gender  ...  eye_id  confidence   diameter
0           1                 -0.04      F  ...       0         1.0  39.079651

[1 rows x 9 columns]

   subject_id  VisualAcuity_logMAR_ Gender  ...  eye_id  confidence   diameter
0           1                 -0.04      F  ...       1    0.999998  41.279886

[1 rows x 9 columns]

   subject_id  VisualAcuity_logMAR_ Gender  ...  eye_id  confidence   diameter
0           2                  -0.1      F  ...       0    0.999429  29.110555

[1 rows x 9 columns]

In [58]:
dataset_features = ['subject_id', 'visual_acuity', 'gender', 'age', 'task_number', 'time', 'eye_id', 'confidence', 'diameter_avg', 'diameter_std']
pupil_dataset = pd.DataFrame(columns=dataset_features)

for pupil_activity in pupil_activities:
    summary = pd.DataFrame({
        'subject_id' : [pupil_activity.iloc[0]['subject_id']],
        'visual_acuity' : [pupil_activity.iloc[0]['VisualAcuity_logMAR_']],
        'gender' : [pupil_activity.iloc[0]['Gender']],
        'age' : [pupil_activity.iloc[0]['Age']],
        'task_number' : [pupil_activity.iloc[0]['task_number']],
        'time' : [pupil_activity['pupil_timestamp'].max() - pupil_activity['pupil_timestamp'].min()],
        'eye_id' : [pupil_activity.iloc[0]['eye_id']],
        'confidence' : [pupil_activity['confidence'].mean()],
        'diameter_avg' : [pupil_activity['diameter'].mean()],
        'diameter_std' : [pupil_activity['diameter'].std()]
    })

    pupil_dataset = pd.concat([pupil_dataset, summary], ignore_index=True)

display(pupil_dataset.head())
print('Dataset length:', len(pupil_dataset))

  subject_id visual_acuity gender  ... confidence diameter_avg diameter_std
0          1         -0.04      F  ...   0.984409    42.766735     3.738708
1          1         -0.04      F  ...   0.986898    44.272847     4.569096
2          1         -0.04      F  ...    0.99916    42.460576     1.521884
3          1         -0.04      F  ...   0.999136    43.401444     1.502215
4          1         -0.04      F  ...    0.94182     42.89046     6.671278

[5 rows x 10 columns]

Dataset length: 376

In [59]:
pupil_dataset = pupil_dataset.merge(annotation_df[['subject_id', 'task_number', 'mental', 'physical', 'temporal', 'performance', 'effort', 'frustration', 'mean']], on=['subject_id', 'task_number'])
pupil_dataset.head()

  subject_id visual_acuity gender age  ... performance effort frustration  mean
0          1         -0.04      F  28  ...        25.0   25.0        10.0  15.0
1          1         -0.04      F  28  ...        25.0   25.0        10.0  15.0
2          1         -0.04      F  28  ...        50.0   15.0        25.0  32.5
3          1         -0.04      F  28  ...        50.0   15.0        25.0  32.5
4          1         -0.04      F  28  ...        80.0   90.0        20.0  62.5

[5 rows x 17 columns]

In [60]:
pupil_dataset = pupil_dataset.drop(columns=['subject_id', 'task_number', 'mental', 'physical', 'temporal', 'performance', 'effort', 'frustration'])
X, y = pupil_dataset.drop(columns=['mean']), pupil_dataset['mean']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, train_size=0.8, random_state=42)

display(X_train.head())
print('Train length:', len(X_train))
display(X_test.head())
print('Test length:', len(X_test))

    visual_acuity gender age  ... confidence diameter_avg diameter_std
109          0.01      F  24  ...   0.964075    30.309942    26.230337
219         -0.01      F  23  ...   0.997959     32.20011      1.45029
350           0.1      M  42  ...   0.794065    29.861537    12.629598
195         -0.08      F  24  ...   0.991292    36.085265     2.048317
75           -0.1      F  36  ...   0.987138    36.026347     1.476166

[5 rows x 8 columns]

Train length: 300

    visual_acuity gender age  ... confidence diameter_avg diameter_std
290         -0.08      M  19  ...   0.989426     35.60951     3.473076
357         -0.08      F  47  ...    0.99295    34.712327     2.741765
261         -0.18      F  28  ...   0.975704    34.051369     2.735571
157         -0.07      M  22  ...   0.857116    34.392244     10.40929
145          -0.1      M  39  ...   0.998243    32.803904     1.356562

[5 rows x 8 columns]

Test length: 76